-- seed.sql
-- One-time seed data for initial game setup.
-- Run AFTER 002_full_schema.sql via Supabase SQL Editor or migration.
--
-- NOTE: player_id is NULL for all nations initially.
-- Create auth users and assign them via the admin UI or setup script.
--
-- Military seed is minimal here. Full military data (templates, formations,
-- units) is generated by the "Import Seed Data" admin Edge Function, which
-- replicates the TypeScript logic from the original server/src/index.ts.

-- ═══════════════════════════════════════════════
-- NATIONS (stable UUIDs for cross-reference)
-- ═══════════════════════════════════════════════
insert into nations (id, name, player_id, gdp, production_units, flag_url, leader_name, leader_picture, population, qol, tax_level, corporate_tax_level, civil_level, army_level, airforce_level, naval_level)
values
  ('a0000000-0000-0000-0000-000000000001', 'Letheia',  null, 480000000, 48000,  'https://placehold.co/156x72/1a1a2e/0ff?text=Letheia',    'Ragnar Hommelson',   'https://placehold.co/400x225/1a1a2e/fff?text=Ragnar+Hommelson',    42000000, 52, 2,2,2,1,1,1),
  ('a0000000-0000-0000-0000-000000000002', 'Valoria',  null, 600000000, 60000,  'https://placehold.co/156x72/1a1a2e/0ff?text=Valoria',    'Marcus Valerius',    'https://placehold.co/400x225/1a1a2e/fff?text=Marcus+Valerius',    55000000, 42, 2,2,2,1,1,1),
  ('a0000000-0000-0000-0000-000000000003', 'Nordmark', null, 360000000, 36000,  'https://placehold.co/156x72/1a1a2e/0ff?text=Nordmark',   'Astrid Bjornsson',   'https://placehold.co/400x225/1a1a2e/fff?text=Astrid+Bjornsson',   35000000, 56, 2,2,2,1,1,1),
  ('a0000000-0000-0000-0000-000000000004', 'Ostland',  null, 400000000, 40000,  'https://placehold.co/156x72/1a1a2e/0ff?text=Ostland',    'Vladimir Ostrov',    'https://placehold.co/400x225/1a1a2e/fff?text=Vladimir+Ostrov',    70000000, 30, 2,2,2,1,1,1),
  ('a0000000-0000-0000-0000-000000000005', 'Sutheria', null, 280000000, 28000,  'https://placehold.co/156x72/1a1a2e/0ff?text=Sutheria',   'Isabella Cruz',      'https://placehold.co/400x225/1a1a2e/fff?text=Isabella+Cruz',      25000000, 62, 2,2,2,1,1,1),
  ('a0000000-0000-0000-0000-000000000006', 'Maridia',  null, 440000000, 44000,  'https://placehold.co/156x72/1a1a2e/0ff?text=Maridia',    'Hassan Al-Marid',    'https://placehold.co/400x225/1a1a2e/fff?text=Hassan+Al-Marid',    48000000, 46, 2,2,2,1,1,1),
  ('a0000000-0000-0000-0000-000000000007', 'Krovia',   null, 320000000, 32000,  'https://placehold.co/156x72/1a1a2e/0ff?text=Krovia',     'Stefan Krovic',      'https://placehold.co/400x225/1a1a2e/fff?text=Stefan+Krovic',      38000000, 36, 2,2,2,1,1,1),
  ('a0000000-0000-0000-0000-000000000008', 'Aetheria', null, 560000000, 56000,  'https://placehold.co/156x72/1a1a2e/0ff?text=Aetheria',   'Elara Voss',         'https://placehold.co/400x225/1a1a2e/fff?text=Elara+Voss',        30000000, 66, 2,2,2,1,1,1)
on conflict (id) do nothing;

-- ═══════════════════════════════════════════════
-- SECTOR MODIFIERS
-- ═══════════════════════════════════════════════
insert into sector_modifiers (nation_id, sector, mod_mult)
select n.id, s.sector, s.mod_mult
from nations n
cross join (values
  ('Agriculture', 1.0), ('Heavy Industry', 1.5), ('Energy', 1.0),
  ('Consumer Goods', 1.5), ('Military & Aerospace', 1.0),
  ('Pharmaceuticals', 0.5), ('Transport & Trade', 2.5)
) as s(sector, mod_mult)
on conflict (nation_id, sector) do nothing;

-- ═══════════════════════════════════════════════
-- COMPANIES
-- ═══════════════════════════════════════════════
insert into companies (id, name, nation_id, profit, subsidies, sector)
values
  -- Letheia (21)
  ('b0010001-0000-0000-0000-000000000001', 'Letheia Agricultural Co',   'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Agriculture'),
  ('b0010001-0000-0000-0000-000000000002', 'Green Valley Farms',         'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Agriculture'),
  ('b0010001-0000-0000-0000-000000000003', 'Letheia Grain Corp',         'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Agriculture'),
  ('b0010001-0000-0000-0000-000000000004', 'Letheia Heavy Industries',   'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Heavy Industry'),
  ('b0010001-0000-0000-0000-000000000005', 'Letheia Steel Works',        'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Heavy Industry'),
  ('b0010001-0000-0000-0000-000000000006', 'Iron Mountain Mining',       'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Heavy Industry'),
  ('b0010001-0000-0000-0000-000000000007', 'Letheia PetroChemical',      'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Energy'),
  ('b0010001-0000-0000-0000-000000000008', 'Letheia Solar Grid',         'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Energy'),
  ('b0010001-0000-0000-0000-000000000009', 'Northern Wind Energy',       'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Energy'),
  ('b0010001-0000-0000-0000-000000000010', 'Royal Letheian Consumer Goods', 'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Consumer Goods'),
  ('b0010001-0000-0000-0000-000000000011', 'Letheia Retail Corp',        'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Consumer Goods'),
  ('b0010001-0000-0000-0000-000000000012', 'Luxor Brands',               'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Consumer Goods'),
  ('b0010001-0000-0000-0000-000000000013', 'Letheia Defense Systems',    'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Military & Aerospace'),
  ('b0010001-0000-0000-0000-000000000014', 'Skyforge Aerospace',         'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Military & Aerospace'),
  ('b0010001-0000-0000-0000-000000000015', 'Letheia Advanced Weapons',   'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Military & Aerospace'),
  ('b0010001-0000-0000-0000-000000000016', 'Letheia Pharm Labs',         'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Pharmaceuticals'),
  ('b0010001-0000-0000-0000-000000000017', 'Aurora Medical',             'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Pharmaceuticals'),
  ('b0010001-0000-0000-0000-000000000018', 'Letheia BioGen',             'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Pharmaceuticals'),
  ('b0010001-0000-0000-0000-000000000019', 'Royal Letheian Shipping',    'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Transport & Trade'),
  ('b0010001-0000-0000-0000-000000000020', 'Letheia Rail Corp',          'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Transport & Trade'),
  ('b0010001-0000-0000-0000-000000000021', 'Air Letheia',                'a0000000-0000-0000-0000-000000000001', 100000000, 0, 'Transport & Trade'),
  -- Valoria (7)
  ('b0020000-0000-0000-0000-000000000001', 'Valorian Farms',             'a0000000-0000-0000-0000-000000000002', 100000000, 0, 'Agriculture'),
  ('b0020000-0000-0000-0000-000000000002', 'Valorian Steel Works',       'a0000000-0000-0000-0000-000000000002', 100000000, 0, 'Heavy Industry'),
  ('b0020000-0000-0000-0000-000000000003', 'Valorian Energy Corp',       'a0000000-0000-0000-0000-000000000002', 100000000, 0, 'Energy'),
  ('b0020000-0000-0000-0000-000000000004', 'Valorian Textiles',          'a0000000-0000-0000-0000-000000000002', 100000000, 0, 'Consumer Goods'),
  ('b0020000-0000-0000-0000-000000000005', 'Valorian Armaments',         'a0000000-0000-0000-0000-000000000002', 100000000, 0, 'Military & Aerospace'),
  ('b0020000-0000-0000-0000-000000000006', 'Valorian Medicinals',        'a0000000-0000-0000-0000-000000000002', 100000000, 0, 'Pharmaceuticals'),
  ('b0020000-0000-0000-0000-000000000007', 'Valorian Shipping Co',       'a0000000-0000-0000-0000-000000000002', 100000000, 0, 'Transport & Trade'),
  -- Nordmark (7)
  ('b0030000-0000-0000-0000-000000000001', 'Nordmark Forestry Corp',     'a0000000-0000-0000-0000-000000000003', 100000000, 0, 'Agriculture'),
  ('b0030000-0000-0000-0000-000000000002', 'Nordmark Engineering',       'a0000000-0000-0000-0000-000000000003', 100000000, 0, 'Heavy Industry'),
  ('b0030000-0000-0000-0000-000000000003', 'Nordmark Hydro Electric',    'a0000000-0000-0000-0000-000000000003', 100000000, 0, 'Energy'),
  ('b0030000-0000-0000-0000-000000000004', 'Nordmark Fisheries',         'a0000000-0000-0000-0000-000000000003', 100000000, 0, 'Consumer Goods'),
  ('b0030000-0000-0000-0000-000000000005', 'Nordmark Defense',           'a0000000-0000-0000-0000-000000000003', 100000000, 0, 'Military & Aerospace'),
  ('b0030000-0000-0000-0000-000000000006', 'Nordmark Pharma',            'a0000000-0000-0000-0000-000000000003', 100000000, 0, 'Pharmaceuticals'),
  ('b0030000-0000-0000-0000-000000000007', 'Nordmark Merchant Fleet',    'a0000000-0000-0000-0000-000000000003', 100000000, 0, 'Transport & Trade'),
  -- Ostland (7)
  ('b0040000-0000-0000-0000-000000000001', 'Ostland Grain Co',           'a0000000-0000-0000-0000-000000000004', 100000000, 0, 'Agriculture'),
  ('b0040000-0000-0000-0000-000000000002', 'Ostland Coal & Steel',       'a0000000-0000-0000-0000-000000000004', 100000000, 0, 'Heavy Industry'),
  ('b0040000-0000-0000-0000-000000000003', 'Ostland Petroleum',          'a0000000-0000-0000-0000-000000000004', 100000000, 0, 'Energy'),
  ('b0040000-0000-0000-0000-000000000004', 'Ostland Manufacturing',      'a0000000-0000-0000-0000-000000000004', 100000000, 0, 'Consumer Goods'),
  ('b0040000-0000-0000-0000-000000000005', 'Ostland Munitions',          'a0000000-0000-0000-0000-000000000004', 100000000, 0, 'Military & Aerospace'),
  ('b0040000-0000-0000-0000-000000000006', 'Ostland Chemical Works',     'a0000000-0000-0000-0000-000000000004', 100000000, 0, 'Pharmaceuticals'),
  ('b0040000-0000-0000-0000-000000000007', 'Ostland Railways',           'a0000000-0000-0000-0000-000000000004', 100000000, 0, 'Transport & Trade'),
  -- Sutheria (7)
  ('b0050000-0000-0000-0000-000000000001', 'Sutheria Agricultural',      'a0000000-0000-0000-0000-000000000005', 100000000, 0, 'Agriculture'),
  ('b0050000-0000-0000-0000-000000000002', 'Sutheria Heavy Machinery',   'a0000000-0000-0000-0000-000000000005', 100000000, 0, 'Heavy Industry'),
  ('b0050000-0000-0000-0000-000000000003', 'Sutheria Power Grid',        'a0000000-0000-0000-0000-000000000005', 100000000, 0, 'Energy'),
  ('b0050000-0000-0000-0000-000000000004', 'Sutheria Textiles',          'a0000000-0000-0000-0000-000000000005', 100000000, 0, 'Consumer Goods'),
  ('b0050000-0000-0000-0000-000000000005', 'Sutheria Defense Corp',      'a0000000-0000-0000-0000-000000000005', 100000000, 0, 'Military & Aerospace'),
  ('b0050000-0000-0000-0000-000000000006', 'Sutheria BioTech',           'a0000000-0000-0000-0000-000000000005', 100000000, 0, 'Pharmaceuticals'),
  ('b0050000-0000-0000-0000-000000000007', 'Sutheria Trade Co',          'a0000000-0000-0000-0000-000000000005', 100000000, 0, 'Transport & Trade'),
  -- Maridia (7)
  ('b0060000-0000-0000-0000-000000000001', 'Maridian Plantations',       'a0000000-0000-0000-0000-000000000006', 100000000, 0, 'Agriculture'),
  ('b0060000-0000-0000-0000-000000000002', 'Maridian Shipyards',         'a0000000-0000-0000-0000-000000000006', 100000000, 0, 'Heavy Industry'),
  ('b0060000-0000-0000-0000-000000000003', 'Maridian Oil Corp',          'a0000000-0000-0000-0000-000000000006', 100000000, 0, 'Energy'),
  ('b0060000-0000-0000-0000-000000000004', 'Maridian Consumer Electronics', 'a0000000-0000-0000-0000-000000000006', 100000000, 0, 'Consumer Goods'),
  ('b0060000-0000-0000-0000-000000000005', 'Maridian Naval Systems',     'a0000000-0000-0000-0000-000000000006', 100000000, 0, 'Military & Aerospace'),
  ('b0060000-0000-0000-0000-000000000006', 'Maridian Pharm Inc',         'a0000000-0000-0000-0000-000000000006', 100000000, 0, 'Pharmaceuticals'),
  ('b0060000-0000-0000-0000-000000000007', 'Maridian Shipping Lines',    'a0000000-0000-0000-0000-000000000006', 100000000, 0, 'Transport & Trade'),
  -- Krovia (7)
  ('b0070000-0000-0000-0000-000000000001', 'Krovia Agricultural Co',     'a0000000-0000-0000-0000-000000000007', 100000000, 0, 'Agriculture'),
  ('b0070000-0000-0000-0000-000000000002', 'Krovian Metallurgical',      'a0000000-0000-0000-0000-000000000007', 100000000, 0, 'Heavy Industry'),
  ('b0070000-0000-0000-0000-000000000003', 'Krovian Coal Energy',        'a0000000-0000-0000-0000-000000000007', 100000000, 0, 'Energy'),
  ('b0070000-0000-0000-0000-000000000004', 'Krovian Consumer Goods',     'a0000000-0000-0000-0000-000000000007', 100000000, 0, 'Consumer Goods'),
  ('b0070000-0000-0000-0000-000000000005', 'Krovian Armory',             'a0000000-0000-0000-0000-000000000007', 100000000, 0, 'Military & Aerospace'),
  ('b0070000-0000-0000-0000-000000000006', 'Krovian Chemical Works',     'a0000000-0000-0000-0000-000000000007', 100000000, 0, 'Pharmaceuticals'),
  ('b0070000-0000-0000-0000-000000000007', 'Krovian Transport Co',       'a0000000-0000-0000-0000-000000000007', 100000000, 0, 'Transport & Trade'),
  -- Aetheria (7)
  ('b0080000-0000-0000-0000-000000000001', 'Aetherian Organic Farms',    'a0000000-0000-0000-0000-000000000008', 100000000, 0, 'Agriculture'),
  ('b0080000-0000-0000-0000-000000000002', 'Aetherian Precision Tools',  'a0000000-0000-0000-0000-000000000008', 100000000, 0, 'Heavy Industry'),
  ('b0080000-0000-0000-0000-000000000003', 'Aetherian Solar Corp',       'a0000000-0000-0000-0000-000000000008', 100000000, 0, 'Energy'),
  ('b0080000-0000-0000-0000-000000000004', 'Aetherian Consumer Products','a0000000-0000-0000-0000-000000000008', 100000000, 0, 'Consumer Goods'),
  ('b0080000-0000-0000-0000-000000000005', 'Aetherian Aerospace',        'a0000000-0000-0000-0000-000000000008', 100000000, 0, 'Military & Aerospace'),
  ('b0080000-0000-0000-0000-000000000006', 'Aetherian Pharmaceuticals',  'a0000000-0000-0000-0000-000000000008', 100000000, 0, 'Pharmaceuticals'),
  ('b0080000-0000-0000-0000-000000000007', 'Aetherian Trade Fleet',      'a0000000-0000-0000-0000-000000000008', 100000000, 0, 'Transport & Trade')
on conflict (id) do nothing;

-- ═══════════════════════════════════════════════
-- ECO HISTORY (turn 0 snapshot)
-- ═══════════════════════════════════════════════
-- GDP = total_company_profits + QoL_tax_at_max_rate
-- QoL tax = 1,200,000,000 * (pop/40M) * (qol/50) * 0.80
insert into eco_history (nation_id, turn_number, gdp, treasury, qol)
select
  n.id, 0,
  (select coalesce(sum(profit), 0) from companies where nation_id = n.id)
    + round(1200000000.0 * (n.population::real / 40000000.0) * (n.qol::real / 50.0) * 0.80),
  n.gdp,
  n.qol
from nations n;

-- ═══════════════════════════════════════════════
-- GAME SETTINGS & TURN 1
-- ═══════════════════════════════════════════════
insert into game_settings (id, turn_duration_hours, starting_gdp, starting_population, starting_qol, base_income_multiplier)
values ('default', 48, 500000, 100000000, 50, 1.0)
on conflict (id) do nothing;

insert into turns (id, number, status, deadline, processed_at)
values ('c0000000-0000-0000-0000-000000000001', 1, 'open', now() + interval '48 hours', null)
on conflict (id) do nothing;

-- ═══════════════════════════════════════════════
-- MILITARY SEED (minimal: one template per unit type per nation)
-- ═══════════════════════════════════════════════
-- Full formations and units are created by the "seed-military" Edge Function
-- after a player claims a nation. This just ensures unit_templates exist
-- for the unit builder to reference.

-- Army types
insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Infantry Battalion', 'army', 'Infantry Battalion', 'Low', 'Low', 'Low', 200000, 2, 3000000
from nations n
on conflict do nothing;

insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Mechanized Battalion', 'army', 'Mechanized Battalion', 'Low', 'Low', 'Low', 400000, 3, 4000000
from nations n
on conflict do nothing;

insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Light Tank Battalion', 'army', 'Light Tank Battalion', 'Low', 'Low', 'Low', 450000, 4, 6000000
from nations n
on conflict do nothing;

insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Medium Tank Battalion', 'army', 'Medium Tank Battalion', 'Low', 'Low', 'Low', 600000, 4, 8000000
from nations n
on conflict do nothing;

insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Heavy Tank Battalion', 'army', 'Heavy Tank Battalion', 'Low', 'Low', 'Low', 1000000, 5, 12000000
from nations n
on conflict do nothing;

insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Artillery Battalion', 'army', 'Artillery Battalion', 'Low', 'Low', 'Low', 500000, 2, 5000000
from nations n
on conflict do nothing;

-- Navy types
insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Destroyer', 'navy', 'Destroyer', 'Low', 'Low', 'Low', 15000000, 2, 6000000
from nations n
where n.name = 'Letheia'
on conflict do nothing;

insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Light Cruiser', 'navy', 'Light Cruiser', 'Low', 'Low', 'Low', 60000000, 4, 20000000
from nations n
where n.name in ('Letheia', 'Valoria', 'Maridia', 'Aetheria')
on conflict do nothing;

insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Battlecruiser', 'navy', 'Battlecruiser', 'Low', 'Low', 'Low', 190000000, 11, 90000000
from nations n
where n.name in ('Letheia', 'Ostland', 'Aetheria')
on conflict do nothing;

insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Battleship', 'navy', 'Battleship', 'Low', 'Low', 'Low', 270000000, 12, 120000000
from nations n
where n.name in ('Letheia', 'Valoria', 'Maridia')
on conflict do nothing;

insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Aircraft Carrier', 'navy', 'Aircraft Carrier', 'Low', 'Low', 'Low', 250000000, 12, 135000000
from nations n
where n.name = 'Letheia'
on conflict do nothing;

insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Attack Submarine', 'navy', 'Attack Submarine', 'Low', 'Low', 'Low', 5000000, 3, 3000000
from nations n
where n.name in ('Letheia', 'Sutheria', 'Maridia')
on conflict do nothing;

-- Air types
insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Fighter Squadron', 'airforce', 'Fighter Squadron', 'Low', 'Low', 'Low', 1000000, 2, 8000000
from nations n
on conflict do nothing;

insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Heavy Fighter Squadron', 'airforce', 'Heavy Fighter Squadron', 'Low', 'Low', 'Low', 1500000, 2, 10000000
from nations n
on conflict do nothing;

insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Light Bomber', 'airforce', 'Light Bomber', 'Low', 'Low', 'Low', 2000000, 3, 10000000
from nations n
on conflict do nothing;

insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Bomber Squadron', 'airforce', 'Bomber Squadron', 'Low', 'Low', 'Low', 4000000, 4, 20000000
from nations n
on conflict do nothing;

insert into unit_templates (id, nation_id, name, branch, unit_type, armor, firepower, speed, build_cost, build_time, upkeep)
select gen_random_uuid(), n.id, 'Standard Flying Boat Squadron', 'airforce', 'Flying Boat Squadron', 'Low', 'Low', 'Low', 1000000, 3, 6000000
from nations n
on conflict do nothing;

-- ═══════════════════════════════════════════════
-- Seed complete
-- ═══════════════════════════════════════════════
select 'Seed complete' as result;
