[build]
  command   = "cd georp-ui && npm install && npm run build"
  publish   = "georp-ui/dist/georp-ui"
  functions = "netlify/functions"  # this is relative to the repo root

[[redirects]]
  from   = "/api/countryReport"
  to     = "/.netlify/functions/countryReport"
  status = 200
  
